package com.parkingmanagement.model.enums;

public enum AlertType {
    LOW_AVAILABILITY,
    PENDING_PAYMENT,
    SYSTEM_ERROR,
    MAINTENANCE_REQUIRED,
    SECURITY_BREACH,
    REVENUE_THRESHOLD,
    OCCUPANCY_THRESHOLD,
    EQUIPMENT_FAILURE,
    USER_ACTIVITY,
    RESERVATION_EXPIRED
}
